version: '3.2'

services:
    zookeeper:
        image: bde2020/pilot-sc4-zookeeper:v0.1.0
        hostname: zookeeper
        container_name: sc4-zookeeper
        environment:
            - MYID=1
        expose:
            - "2181"
        ports:
            - "2181:2181"
        networks:
          - pilot-sc4-net
    
    kafka:
        image: bde2020/pilot-sc4-kafka:v0.1.0
        hostname: kafka
        container_name: sc4-kafka
        environment:
            - SERVICE_PRECONDITION=zookeeper:2181
            - ZOOKEEPER_SERVERS=zookeeper:2181
            - INITIAL_TOPICS="taxi" 
        depends_on:
            - zookeeper
        expose:
            - "9092"
        networks:
          - pilot-sc4-net

    fcd-producer:
        image: bde2020/pilot-sc4-fcd-producer:v0.1.0
        container_name: fcd-producer
        environment:
          - ZOOKEEPER_SERVERS=zookeeper:2181
        depends_on:
            - kafka
        networks:
          - pilot-sc4-net

networks:
    pilot-sc4-net:
      external: true
